/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inicioSesion.InicioSesion;
import EstructurasAux.ItemInventario;
import EstructurasAux.cotizaciones;
import EstructurasAux.itemsOrdenCompra;
import EstructurasAux.itemxproveedor;
import EstructurasAux.proveedor;
import EstructurasAux.solicitudPr;
import interfaces.Usuario;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author Oscar_Malagon
 */
public class AOficina extends javax.swing.JFrame {

    private static BigDecimal id = null;
    private static String area = null;
    private static GregorianCalendar hoy = new GregorianCalendar();

    /**
     * Creates new form administrador
     *
     * @param ide
     */
    public AOficina(String ide) {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setSize(this.getMaximumSize());
        initComponents();
        setIcon();
        id = new BigDecimal(ide);

        this.fecha.setText(hoy.get(Calendar.DAY_OF_MONTH) + "/" + (hoy.get(Calendar.MONTH) + 1) + "/" + hoy.get(Calendar.YEAR));
        Usuario u = cliente.Cliente.conectarU();
        String user = null;
        try {
            user = u.getUsuario(id);
            area = u.area(id);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ArrayList<proveedor> todosProveedores = u.todosProveedores();
            for (proveedor p : todosProveedores) {
                this.Apro_NITProv.addItem(p.getNIT());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.AreaProcesoSolicitante.setText(area);
        this.AreaProcesoSolicitante.setEditable(false);
        this.NombreSolicitante.setText(user);
        this.NombreSolicitante.setEditable(false);
        this.RefrescarInven.doClick();
        this.BotonRefrescarSolRev.doClick();
//Función desactivada temporalmente
        this.TabbedPaneUsuarios.setSelectedIndex(0);
        this.jTabbedPane2.disable();
//---
        this.BotonRefrescarSol.doClick();

    }

    private AOficina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdministrador = new javax.swing.JLabel();
        ButtonCerrarSesion = new javax.swing.JButton();
        TabbedPaneUsuarios = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BotonEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        BotonVerItems = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Observaciones = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        AreaProcesoSolicitante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NombreSolicitante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVerProveedores = new javax.swing.JTable();
        botonAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaIngresarItems = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tabbedReportes = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        RefrescarInven = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        VolverASol = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaSolicitudesRev = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaSolicitudesNoRev = new javax.swing.JTable();
        BotonRefrescarSol = new javax.swing.JButton();
        BotonRevisar1 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        BotonCotizar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaSolicitudesRev = new javax.swing.JTable();
        BotonRefrescarSolRev = new javax.swing.JButton();
        btnRealizarOrden = new javax.swing.JButton();
        btnAyudaOrden = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btnVerProv = new javax.swing.JButton();
        Apro_NITProv = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaitemsCot = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        numeroSolicitudCot = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fechaCot = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        areaCot = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nombreCot = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablaProveedoresCot = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        obsCot = new javax.swing.JTextField();
        BotonRevisar = new javax.swing.JButton();
        BotonAyudaCot = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        fechaOrden = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        oc_nomProv = new javax.swing.JLabel();
        oc_nit = new javax.swing.JLabel();
        oc_dir = new javax.swing.JLabel();
        oc_cel = new javax.swing.JLabel();
        oc_fax = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaDatosPedido = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        obsOrden = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        numorden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAdministrador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelAdministrador.setText("Auxiliar de Oficina");

        ButtonCerrarSesion.setText("Cerrar Sesión");
        ButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarSesionActionPerformed(evt);
            }
        });

        TabbedPaneUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonEnviar.setText("Enviar Solicitud");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Diligencie el siguiente formato");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fecha");

        fecha.setText("jLabel3");

        BotonVerItems.setText("Ver Inventario");
        BotonVerItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerItemsActionPerformed(evt);
            }
        });

        jLabel3.setText("Nota: Si necesita algún ítem que no se encuentre en el inventario,");

        jLabel5.setText("Observaciones");

        jLabel6.setText("Area o Proceso solicitante");

        AreaProcesoSolicitante.setText("jTextField1");
        AreaProcesoSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaProcesoSolicitanteActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre del Solicitante");

        NombreSolicitante.setText("jTextField2");

        tablaVerProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Disponibilidad", "Observación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVerProveedores);
        if (tablaVerProveedores.getColumnModel().getColumnCount() > 0) {
            tablaVerProveedores.getColumnModel().getColumn(1).setMinWidth(20);
            tablaVerProveedores.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        botonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 0, 255));
        botonAgregar.setText("+");
        botonAgregar.setMaximumSize(new java.awt.Dimension(50, 25));
        botonAgregar.setMinimumSize(new java.awt.Dimension(50, 25));
        botonAgregar.setPreferredSize(new java.awt.Dimension(50, 25));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel8.setText("Items");

        tablaIngresarItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab", "Codigo", "Descripción", "Cantidad", "Presentación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaIngresarItems);
        if (tablaIngresarItems.getColumnModel().getColumnCount() > 0) {
            tablaIngresarItems.getColumnModel().getColumn(0).setMaxWidth(45);
            tablaIngresarItems.getColumnModel().getColumn(1).setMinWidth(20);
            tablaIngresarItems.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        jLabel9.setText("Proveedores");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("-");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText(" debe comunicarse directamente con el Director Administrativo. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fecha)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonVerItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEnviar))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Observaciones)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AreaProcesoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaProcesoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonEnviar)
                        .addComponent(BotonVerItems))
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Pedido", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        TabbedPaneUsuarios.addTab("RealizarSolicitudes", jPanel4);

        RefrescarInven.setText("Refrescar");
        RefrescarInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarInvenActionPerformed(evt);
            }
        });

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Presentación", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(tablaInventario);

        VolverASol.setText("Volver a Solicitudes");
        VolverASol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverASolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefrescarInven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VolverASol)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefrescarInven)
                    .addComponent(VolverASol))
                .addContainerGap())
        );

        tabbedReportes.addTab("Ver Inventario", jPanel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Solicitudes no revisadas");

        tablaSolicitudesRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Solicitud", "Fecha", "Observaciones", "Responsable Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaSolicitudesRev);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Solicitudes revisadas");

        tablaSolicitudesNoRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Solicitud", "Fecha", "Observaciones", "Responsable Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaSolicitudesNoRev);

        BotonRefrescarSol.setText("Refrescar");
        BotonRefrescarSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRefrescarSolActionPerformed(evt);
            }
        });

        BotonRevisar1.setText("Marcar como no revisada");
        BotonRevisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevisar1ActionPerformed(evt);
            }
        });

        BotonCotizar.setText("Realizar Cotizacion");
        BotonCotizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCotizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonRefrescarSol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonRevisar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonCotizar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(BotonCotizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRevisar1)
                .addGap(16, 16, 16)
                .addComponent(BotonRefrescarSol)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(469, Short.MAX_VALUE)))
        );

        tabbedReportes.addTab("Solicitudes", jPanel6);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Descripción");

        jLabel19.setText("Esta pestaña le permite ver las solicitudes que han sido aprobadas por el Director Administrativo Comercial");

        TablaSolicitudesRev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Cotización", "Aux Oficina", "Resp. Área", "Proveedor", "Inv", "Código", "Cant. Solicitada", "Cant. Aprobada", "Precio Unitario", "Num Solicitud"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(TablaSolicitudesRev);

        BotonRefrescarSolRev.setText("Refrescar");
        BotonRefrescarSolRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRefrescarSolRevActionPerformed(evt);
            }
        });

        btnRealizarOrden.setText("Realizar Orden Compra");
        btnRealizarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarOrdenActionPerformed(evt);
            }
        });

        btnAyudaOrden.setText("Ayuda");
        btnAyudaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaOrdenActionPerformed(evt);
            }
        });

        jLabel28.setText("Ingrese el NIT del proveedor ");

        btnVerProv.setText("Ver Listado de Proveedores");
        btnVerProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProvActionPerformed(evt);
            }
        });

        Apro_NITProv.setMaximumRowCount(3);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRealizarOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonRefrescarSolRev))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addComponent(btnAyudaOrden))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Apro_NITProv, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerProv)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAyudaOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(btnVerProv)
                    .addComponent(Apro_NITProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRefrescarSolRev)
                    .addComponent(btnRealizarOrden))
                .addContainerGap())
        );

        tabbedReportes.addTab("Aprobadas", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportes)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportes)
        );

        TabbedPaneUsuarios.addTab("Reportes", jPanel2);

        tablaitemsCot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv Actual", "Lab", "Código", "Descripción", "Cantidad Solicitada", "Presentación", "Precio Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaitemsCot);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("N° Solicitud");

        numeroSolicitudCot.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Fecha");

        fechaCot.setText("jLabel15");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Area o proceso Solicitante");

        areaCot.setText("jLabel17");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Nombre de Solicitante");

        nombreCot.setText("jLabel19");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Seleccione el proveedor.");

        tablaProveedoresCot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Nombre", "Precio", "Disponibilidad", "Observación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tablaProveedoresCot);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Observaciones");

        BotonRevisar.setText("Enviar Cotización");
        BotonRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevisarActionPerformed(evt);
            }
        });

        BotonAyudaCot.setText("Ayuda");
        BotonAyudaCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAyudaCotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obsCot, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaCot)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(numeroSolicitudCot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonAyudaCot))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCot)
                            .addComponent(areaCot)))
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotonRevisar)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(numeroSolicitudCot))
                    .addComponent(BotonAyudaCot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaCot)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaCot)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCot)
                    .addComponent(jLabel18))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obsCot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(BotonRevisar)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TabbedPaneUsuarios.addTab("Cotizaciones", jPanel7);

        jLabel20.setText("Fecha");

        fechaOrden.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos Proveedor");

        jLabel23.setText("Nombre Proveedor/Prestador del servicio");

        jLabel24.setText("NIT");

        jLabel25.setText("Dirección");

        jLabel26.setText("Celular");

        jLabel27.setText("Telefax");

        oc_nomProv.setText("jLabel30");

        oc_nit.setText("jLabel31");

        oc_dir.setText("jLabel32");

        oc_cel.setText("jLabel33");

        oc_fax.setText("jLabel34");

        tablaDatosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Interno", "Descripción", "Cantidad", "Presentación", "Valor Unitario", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tablaDatosPedido);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Datos Pedido");

        jLabel36.setText("Subtotal (Antes de IVA)");

        subtotal.setText("jLabel37");

        jLabel40.setText("Total");

        total.setText("jLabel41");

        jLabel42.setText("Observaciones");

        obsOrden.setColumns(20);
        obsOrden.setRows(5);
        jScrollPane10.setViewportView(obsOrden);

        jButton1.setText("Generar .pdf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Numero de Orden");

        numorden.setText("jLabel28");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(fechaOrden)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(oc_nomProv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numorden))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel23)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addGap(256, 256, 256)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oc_nit)
                                    .addComponent(oc_dir)
                                    .addComponent(oc_cel)
                                    .addComponent(oc_fax)))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel36)
                                    .addGap(100, 100, 100)
                                    .addComponent(subtotal))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fechaOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(oc_nomProv)
                    .addComponent(numorden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(oc_nit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(oc_dir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(oc_cel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(oc_fax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        TabbedPaneUsuarios.addTab("Orden Compra", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonCerrarSesion))
                    .addComponent(TabbedPaneUsuarios))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAdministrador)
                    .addComponent(ButtonCerrarSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneUsuarios)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionActionPerformed
        InicioSesion i = new InicioSesion();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCerrarSesionActionPerformed

    private void BotonAyudaCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaCotActionPerformed
        JOptionPane.showMessageDialog(areaCot, "Antes de enviar la cotización debe seleccionar"
                + "todas las filas que desea actualizar. \nPuede ayudarse con el boton Ctrl");
    }//GEN-LAST:event_BotonAyudaCotActionPerformed

    private void BotonRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevisarActionPerformed
        Usuario u = cliente.Cliente.conectarU();
        boolean act = false;
        boolean actPrecio = false;
        DefaultTableModel df = (DefaultTableModel) this.tablaSolicitudesNoRev.getModel();
        DefaultTableModel df_itemsCot = (DefaultTableModel) this.tablaitemsCot.getModel();
        int filaSolicitud = this.tablaSolicitudesNoRev.getSelectedRow();
        int itemsAct[] = this.tablaitemsCot.getSelectedRows();
        BigDecimal numSol = (BigDecimal) df.getValueAt(filaSolicitud, 0);
        String lab;
        BigDecimal codigo;
        float precio;
        for (int ite : itemsAct) {
            lab = (String) df_itemsCot.getValueAt(ite, 1);
            codigo = new BigDecimal(df_itemsCot.getValueAt(ite, 2).toString());
            precio = new Float(df_itemsCot.getValueAt(ite, 6).toString());
            try {
                System.out.println(id + " " + codigo + " " + lab + " " + numSol + " " + precio);
                actPrecio = u.generarCotizacion(id, "1", codigo, lab, numSol, precio);
            } catch (RemoteException ex) {
                Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            act = u.RevisarSolicitud(this.id, numSol, "SI");
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (act == true && actPrecio == true) {
            JOptionPane.showMessageDialog(rootPane, "Hecho!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error Actualizando");
        }
        this.BotonRefrescarSol.doClick();
    }//GEN-LAST:event_BotonRevisarActionPerformed

    private void BotonCotizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCotizarActionPerformed
        Usuario u = cliente.Cliente.conectarU();

        DefaultTableModel df = (DefaultTableModel) this.tablaSolicitudesNoRev.getModel();
        DefaultTableModel df_items = (DefaultTableModel) this.tablaitemsCot.getModel();
        DefaultTableModel df_proveedores = (DefaultTableModel) this.tablaProveedoresCot.getModel();
        int filaSeleccionada = this.tablaSolicitudesNoRev.getSelectedRow();
        BigDecimal numSol = (BigDecimal) df.getValueAt(filaSeleccionada, 0);
        solicitudPr solicitud_NumSol = null;
        try {
            solicitud_NumSol = u.getSolicitud_NumSol(numSol);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        GregorianCalendar fecha = solicitud_NumSol.getFecha();
        ArrayList<ItemInventario> items_numSol = null;
        try {
            items_numSol = u.getItems_numSol(numSol);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<ArrayList<itemxproveedor>> aux = new ArrayList<>();
        ArrayList<itemxproveedor> itemxproveedor = null;
        for (int i = df_items.getRowCount() - 1; i >= 0; i--) {
            df_items.removeRow(i);
        }
        this.numeroSolicitudCot.setText(numSol.toString());
        this.fechaCot.setText(fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
        this.areaCot.setText(solicitud_NumSol.getArea());
        this.nombreCot.setText(solicitud_NumSol.getNombreRA());
        this.TabbedPaneUsuarios.setSelectedIndex(2);
        for (ItemInventario i : items_numSol) {
            Vector datos = new Vector();
            datos.add(i.getCantidad());
            datos.add(i.getInventario());
            datos.add(i.getNumero());
            datos.add(i.getDescripcion());
            datos.add(i.getCantidadSolicitada());
            datos.add(i.getPresentacion());
            df_items.addRow(datos);
            try {
                itemxproveedor = u.getItemxproveedor(i.getInventario(), new BigDecimal(i.getNumero()));
            } catch (RemoteException ex) {
                Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
            }
            aux.add(itemxproveedor);
        }
        for (ArrayList<itemxproveedor> iter : aux) {
            for (itemxproveedor i : iter) {
                Vector datos = new Vector();
                datos.add(i.getNIT());
                datos.add(i.getNombre());
                datos.add(i.getPrecio());
                datos.add(i.getDisponibilidad());
                df_proveedores.addRow(datos);
            }
        }
        this.obsCot.setText(solicitud_NumSol.getObservaciones());
    }//GEN-LAST:event_BotonCotizarActionPerformed

    private void BotonRevisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevisar1ActionPerformed
        Usuario u = cliente.Cliente.conectarU();
        boolean act = false;
        DefaultTableModel df = (DefaultTableModel) this.tablaSolicitudesRev.getModel();
        int filaSeleccionadas[] = this.tablaSolicitudesRev.getSelectedRows();
        for (int filaSeleccionada : filaSeleccionadas) {
            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione una fila");
            } else {
                BigDecimal numSol = (BigDecimal) df.getValueAt(filaSeleccionada, 0);
                try {
                    act = u.RevisarSolicitud(null, numSol, "NO");
                } catch (RemoteException ex) {
                    Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (act == true) {
            JOptionPane.showMessageDialog(rootPane, "Hecho!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error Actualizando");
        }
        this.BotonRefrescarSol.doClick();
    }//GEN-LAST:event_BotonRevisar1ActionPerformed

    private void BotonRefrescarSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRefrescarSolActionPerformed
        DefaultTableModel df_NoRevisadas = (DefaultTableModel) this.tablaSolicitudesNoRev.getModel();
        Usuario u = cliente.Cliente.conectarU();
        for (int i = df_NoRevisadas.getRowCount() - 1; i >= 0; i--) {
            df_NoRevisadas.removeRow(i);
        }
        ArrayList<solicitudPr> solNoRev = null;
        try {
            solNoRev = u.getNoRevisadas();
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        GregorianCalendar fecha = new GregorianCalendar();
        for (solicitudPr s : solNoRev) {
            fecha = s.getFecha();
            Vector datos = new Vector();
            datos.add(s.getSolicitudpr_id());
            datos.add(fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
            datos.add(s.getObservaciones());
            datos.add(s.getNombreRA());
            df_NoRevisadas.addRow(datos);
        }
        //---------------------------------------------------------------------
        DefaultTableModel df_Revisadas = (DefaultTableModel) this.tablaSolicitudesRev.getModel();
        for (int i = df_Revisadas.getRowCount() - 1; i >= 0; i--) {
            df_Revisadas.removeRow(i);
        }
        ArrayList<solicitudPr> solRev = null;
        try {
            solRev = u.getRevisadas();
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        GregorianCalendar fecha1 = new GregorianCalendar();
        for (solicitudPr s : solRev) {
            fecha1 = s.getFecha();
            Vector datos = new Vector();
            datos.add(s.getSolicitudpr_id());
            datos.add(fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
            datos.add(s.getObservaciones());
            datos.add(s.getNombreRA());
            df_Revisadas.addRow(datos);
        }

    }//GEN-LAST:event_BotonRefrescarSolActionPerformed

    private void VolverASolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverASolActionPerformed
        this.TabbedPaneUsuarios.setSelectedIndex(0);
        this.jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_VolverASolActionPerformed

    private void RefrescarInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarInvenActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaInventario.getModel();
        for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        Usuario u = cliente.Cliente.conectarU();

        ArrayList<ItemInventario> itemInventario = null;
        try {
            itemInventario = u.itemInventario(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (ItemInventario i : itemInventario) {
            Vector<Object> aux = new Vector<>();
            try {
                aux.add(0, u.area(this.id) + "-" + i.getNumero());
            } catch (RemoteException ex) {
                Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
            }
            aux.add(1, i.getDescripcion());
            aux.add(2, i.getPresentacion());
            aux.add(3, i.getCantidad());
            df.addRow(aux);
        }
    }//GEN-LAST:event_RefrescarInvenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaIngresarItems.getModel();
        if (df.getRowCount() > 0) {
            df.removeRow(this.tablaIngresarItems.getSelectedRow());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Usuario u = cliente.Cliente.conectarU();

        ArrayList<ItemInventario> itemInventario = null;
        try {
            itemInventario = u.itemInventario(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector elementos = new Vector();
        JList list;
        DefaultTableModel df;
        for (ItemInventario i : itemInventario) {
            elementos.add(i.getNumero());
        }
        list = new JList(elementos);
        JOptionPane elegir = new JOptionPane();
        elegir.showConfirmDialog(null, list, "Seleccione el código del ítem", elegir.PLAIN_MESSAGE);
        if (list.getSelectedIndex() != -1) {
            df = (DefaultTableModel) this.tablaIngresarItems.getModel();
            df.addRow(new Object[]{Boolean.FALSE, null, null});
            for (int i = 0; i < df.getRowCount(); i++) {
                df.setValueAt(this.AreaProcesoSolicitante.getText() + "-", i, 0);
            }

            ItemInventario i = itemInventario.get(list.getSelectedIndex());
            df.setValueAt(i.getNumero(), df.getRowCount() - 1, 1);
            df.setValueAt(i.getDescripcion(), df.getRowCount() - 1, 2);
            df.setValueAt(i.getPresentacion(), df.getRowCount() - 1, 3);
            df.setValueAt(i.getCantidad(), df.getRowCount() - 1, 4);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void AreaProcesoSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaProcesoSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaProcesoSolicitanteActionPerformed

    private void BotonVerItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerItemsActionPerformed
        this.RefrescarInven.doClick();
        this.TabbedPaneUsuarios.setSelectedIndex(1);
        this.tabbedReportes.setSelectedIndex(0);
    }//GEN-LAST:event_BotonVerItemsActionPerformed

    private void BotonRefrescarSolRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRefrescarSolRevActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.TablaSolicitudesRev.getModel();
Usuario u = cliente.Cliente.conectarU();
for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        ArrayList<cotizaciones> cotizacione = null;
        try {
            cotizacione = u.getCotizaciones("SI");
            for (cotizaciones c : cotizacione) {
                Vector datos = new Vector();
                datos.add(c.getCotizacionId());
                datos.add(c.getAO());
                datos.add(c.getRA());
                datos.add(c.getProveedor());
                datos.add(c.getLab());
                datos.add(c.getCinterno());
                datos.add(c.getCantSol());
                datos.add(new Float(u.getCantAprobada(c).toString()));
                datos.add(c.getPrecioUnitario());
                datos.add(c.getNumSol());
                df.addRow(datos);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonRefrescarSolRevActionPerformed

    private void btnRealizarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarOrdenActionPerformed
        Usuario u = cliente.Cliente.conectarU();
        this.TabbedPaneUsuarios.setSelectedIndex(3);
        this.fechaOrden.setText(hoy.get(Calendar.DAY_OF_MONTH) + "/" + (hoy.get(Calendar.MONTH) + 1) + "/" + hoy.get(Calendar.YEAR));
        int selectedRow = this.TablaSolicitudesRev.getSelectedRow();
        String proveedor = this.Apro_NITProv.getSelectedItem().toString();
        DefaultTableModel df = (DefaultTableModel) this.tablaDatosPedido.getModel();
        float total = 0;
        String com = "";
        ArrayList<itemsOrdenCompra> pedidoOrdenCompra = new ArrayList<>();
        try {
            proveedor prov = u.getDatosProveedor(proveedor);
            if (prov != null) {
                this.oc_nomProv.setText(prov.getNombre());
                this.oc_nit.setText(prov.getNIT());
                this.oc_dir.setText(prov.getDireccion());
                this.oc_cel.setText(new Integer(prov.getTelefono()).toString());
                this.oc_fax.setText(new Integer(prov.getTelefax()).toString());
                pedidoOrdenCompra = u.pedidoOrdenCompra(proveedor);
                for (itemsOrdenCompra p : pedidoOrdenCompra) {
                    Vector datos = new Vector();
                    datos.add(p.getCinterno());
                    datos.add(p.getInventario());
                    datos.add(p.getCaprobada());
                    datos.add(p.getPresen());
                    datos.add(p.getPrecioU());
                    datos.add(p.getvTotal());
                    total += p.getvTotal();
                    com += p.getObs() + " // ";
                    df.addRow(datos);
                }
            }
            this.total.setText(new Float(total).toString());
            this.subtotal.setText(new Float(total).toString());
            this.obsOrden.setText(com);
            u.crearOrdenCompra(this.id);
            BigDecimal numOrden = u.OrdenValida(id);
            this.numorden.setText(numOrden.toString());
            boolean valido = u.itemsxorden(numOrden, proveedor, pedidoOrdenCompra, com);
            if (valido == true) {
                JOptionPane.showMessageDialog(null, "Hecho...Numero de Orden: " + numOrden.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error!");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRealizarOrdenActionPerformed

    private void btnAyudaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaOrdenActionPerformed
        String msg = "Debe seleccionar el NIT del proveedor al cual le va a realizar un pedido";
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_btnAyudaOrdenActionPerformed

    private void btnVerProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProvActionPerformed
        Usuario u = cliente.Cliente.conectarU();
        try {
            ArrayList<proveedor> todosProveedores = u.todosProveedores();
            ArrayList<Vector> tabla = new ArrayList<>();
            for (proveedor t : todosProveedores) {
                Vector datos = new Vector();
                datos.add(t.getNIT());
                datos.add(t.getNombre());
                tabla.add(datos);
            }
            verProveedores ver = new verProveedores(tabla);
            ver.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerProvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Usuario u = cliente.Cliente.conectarU();
            proveedor p = new proveedor(this.oc_nomProv.getText(), this.oc_nit.getText(), this.oc_dir.getText(), new Integer(this.oc_cel.getText()), new Integer(this.oc_fax.getText()));
            ArrayList<itemsOrdenCompra> pedidoOrdenCompra = u.pedidoOrdenCompra(this.oc_nit.getText());
            float total = new Float(this.total.getText());
            String obs = this.obsOrden.getText();
            String numorden = this.numorden.getText();
            File pdf_002 = u.pdf_002(p, pedidoOrdenCompra, total, obs, numorden);
            Desktop.getDesktop().open(pdf_002);
        } catch (RemoteException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AOficina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AOficina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AOficina().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconB.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Apro_NITProv;
    private javax.swing.JTextField AreaProcesoSolicitante;
    private javax.swing.JButton BotonAyudaCot;
    private javax.swing.JButton BotonCotizar;
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JButton BotonRefrescarSol;
    private javax.swing.JButton BotonRefrescarSolRev;
    private javax.swing.JButton BotonRevisar;
    private javax.swing.JButton BotonRevisar1;
    private javax.swing.JButton BotonVerItems;
    private javax.swing.JButton ButtonCerrarSesion;
    private javax.swing.JTextField NombreSolicitante;
    private javax.swing.JTextField Observaciones;
    private javax.swing.JButton RefrescarInven;
    private javax.swing.JTabbedPane TabbedPaneUsuarios;
    private javax.swing.JTable TablaSolicitudesRev;
    private javax.swing.JButton VolverASol;
    private javax.swing.JLabel areaCot;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton btnAyudaOrden;
    private javax.swing.JButton btnRealizarOrden;
    private javax.swing.JButton btnVerProv;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fechaCot;
    private javax.swing.JLabel fechaOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelAdministrador;
    private javax.swing.JLabel nombreCot;
    private javax.swing.JLabel numeroSolicitudCot;
    private javax.swing.JLabel numorden;
    private javax.swing.JTextField obsCot;
    private javax.swing.JTextArea obsOrden;
    private javax.swing.JLabel oc_cel;
    private javax.swing.JLabel oc_dir;
    private javax.swing.JLabel oc_fax;
    private javax.swing.JLabel oc_nit;
    private javax.swing.JLabel oc_nomProv;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTabbedPane tabbedReportes;
    private javax.swing.JTable tablaDatosPedido;
    private javax.swing.JTable tablaIngresarItems;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaProveedoresCot;
    private javax.swing.JTable tablaSolicitudesNoRev;
    private javax.swing.JTable tablaSolicitudesRev;
    private javax.swing.JTable tablaVerProveedores;
    private javax.swing.JTable tablaitemsCot;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
