/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import inicioSesion.InicioSesion;
import EstructurasAux.solicitudPr;
import EstructurasAux.ItemInventario;
import EstructurasAux.itemRecep;
import EstructurasAux.itemsOrdenCompra;
import EstructurasAux.proveedor;
import EstructurasAux.recepcionProd;
import EstructurasAux.solicitudServ;
import com.toedter.calendar.JDateChooserCellEditor;
import interfaces.Usuario;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Oscar_Malagon
 */
public class RArea extends javax.swing.JFrame {

    private static BigDecimal id = null;
    private static String area = null;
    private static GregorianCalendar hoy = new GregorianCalendar();
    private ArrayList<ItemInventario> itemsSolicitud = new ArrayList<>();
    private static String cadenaFecha=  hoy.get(Calendar.DAY_OF_MONTH) + "/" + (hoy.get(Calendar.MONTH) + 1) + "/" + hoy.get(Calendar.YEAR);

    /**
     * Creates new form administrador
     *
     * @param ide
     */
    public RArea(String ide) {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setSize(this.getMaximumSize());
        initComponents();
        setIcon();
        id = new BigDecimal(ide);
        this.fecha.setText(cadenaFecha);
        this.fecha1.setText(cadenaFecha);
        this.recFecha.setText(cadenaFecha);
        Usuario u = cliente.Cliente.conectarU();
        String user = null;
        try {
            user = u.getUsuario(id);
            area = u.area(id);

        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.AreaProcesoSolicitante.setText(area);
        this.AreaProcesoSolicitante.setEditable(false);
        this.AreaProcesoSolicitante1.setText(area);
        this.AreaProcesoSolicitante1.setEditable(false);
        this.NombreSolicitante.setText(user);
        this.NombreSolicitante.setEditable(false);
        this.NombreSolicitante1.setText(user);
        this.NombreSolicitante1.setEditable(false);
        this.RefrescarInven.doClick();
        TableColumn fecRec = this.tablaDatosPedido.getColumnModel().getColumn(7);
        fecRec.setCellEditor(new JDateChooserCellEditor());
        TableColumn fecVen = this.tablaDatosPedido.getColumnModel().getColumn(10);
        fecVen.setCellEditor(new JDateChooserCellEditor());
    }

    private RArea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdministrador = new javax.swing.JLabel();
        ButtonCerrarSesion = new javax.swing.JButton();
        TabbedPaneUsuarios = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BotonEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        BotonVerItems = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Observaciones = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        AreaProcesoSolicitante = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NombreSolicitante = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaIngresarItems = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        BotonEnviar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JLabel();
        BotonVerItems1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Observaciones1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        AreaProcesoSolicitante1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NombreSolicitante1 = new javax.swing.JTextField();
        botonAgregar1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaItemsServicios = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        tabbedReportes = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        RefrescarInven = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        VolverASol = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVerSolicitudes = new javax.swing.JTable();
        RefrescarSolicitudes = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        recFecha = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rec_nomProv = new javax.swing.JLabel();
        rec_nit = new javax.swing.JLabel();
        rec_dir = new javax.swing.JLabel();
        rec_cel = new javax.swing.JLabel();
        rec_fax = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaDatosPedido = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        recobs = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        numorden = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnProcesarRec = new javax.swing.JButton();
        btnEnviarRec = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelAdministrador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelAdministrador.setText("Responsable Área");

        ButtonCerrarSesion.setText("Cerrar Sesión");
        ButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarSesionActionPerformed(evt);
            }
        });

        TabbedPaneUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonEnviar.setText("Enviar Solicitud");
        BotonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Diligencie el siguiente formato");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fecha");

        fecha.setText("jLabel3");

        BotonVerItems.setText("Ver Inventario");
        BotonVerItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerItemsActionPerformed(evt);
            }
        });

        jLabel3.setText("Nota: Si necesita algún ítem que no se encuentre en el inventario,");

        jLabel5.setText("Observaciones");

        jLabel6.setText("Area o Proceso solicitante");

        AreaProcesoSolicitante.setText("jTextField1");

        jLabel7.setText("Nombre del Solicitante");

        NombreSolicitante.setText("jTextField2");

        botonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 0, 255));
        botonAgregar.setText("+");
        botonAgregar.setMaximumSize(new java.awt.Dimension(50, 25));
        botonAgregar.setMinimumSize(new java.awt.Dimension(50, 25));
        botonAgregar.setPreferredSize(new java.awt.Dimension(50, 25));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        jLabel8.setText("Items");

        tablaIngresarItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab", "Codigo", "Descripción", "Cantidad Actual", "Presentación", "Cantidad Solicitada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaIngresarItems);
        if (tablaIngresarItems.getColumnModel().getColumnCount() > 0) {
            tablaIngresarItems.getColumnModel().getColumn(0).setMaxWidth(45);
            tablaIngresarItems.getColumnModel().getColumn(1).setMinWidth(20);
            tablaIngresarItems.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("-");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(50, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText(" debe comunicarse directamente con el Director Administrativo. ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BotonVerItems)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEnviar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fecha))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Observaciones)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NombreSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(AreaProcesoSolicitante))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jSeparator4)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaProcesoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonEnviar)
                        .addComponent(BotonVerItems))
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Productos", jPanel1);

        BotonEnviar1.setText("Enviar Solicitud");
        BotonEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEnviar1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Diligencie el siguiente formato");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Fecha");

        fecha1.setText("jLabel3");

        BotonVerItems1.setText("Ver Inventario");
        BotonVerItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerItems1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nota: Si necesita algún ítem que no se encuentre en el inventario,");

        jLabel13.setText("Observaciones");

        jLabel14.setText("Area o Proceso solicitante");

        AreaProcesoSolicitante1.setText("jTextField1");

        jLabel15.setText("Nombre del Solicitante");

        NombreSolicitante1.setText("jTextField2");

        botonAgregar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonAgregar1.setForeground(new java.awt.Color(0, 0, 255));
        botonAgregar1.setText("+");
        botonAgregar1.setMaximumSize(new java.awt.Dimension(50, 25));
        botonAgregar1.setMinimumSize(new java.awt.Dimension(50, 25));
        botonAgregar1.setPreferredSize(new java.awt.Dimension(50, 25));
        botonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Items");

        tablaItemsServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lab", "Codigo", "Descripción", "Especificaciones Técnicas del Servicio", "Personal Calificado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaItemsServicios);
        if (tablaItemsServicios.getColumnModel().getColumnCount() > 0) {
            tablaItemsServicios.getColumnModel().getColumn(0).setMaxWidth(45);
            tablaItemsServicios.getColumnModel().getColumn(1).setMinWidth(20);
            tablaItemsServicios.getColumnModel().getColumn(1).setPreferredWidth(70);
        }

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("-");
        jButton3.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel17.setText(" debe comunicarse directamente con el Director Administrativo. ");

        jLabel18.setText("Especificaciones del Servicio");

        jCheckBox1.setText("Calibración");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Calificación");

        jCheckBox4.setText("Fumigación");

        jCheckBox3.setText("Mantenimiento Preventivo");

        jCheckBox5.setText("Mantenimiento Correctivo");

        jCheckBox6.setText("Lavado Tanques");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(BotonVerItems1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonEnviar1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fecha1))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Observaciones1)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NombreSolicitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AreaProcesoSolicitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 87, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(fecha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaProcesoSolicitante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(botonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreSolicitante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox5))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Observaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(95, 95, 95)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonEnviar1)
                        .addComponent(BotonVerItems1))
                    .addComponent(jLabel17))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Servicio", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        TabbedPaneUsuarios.addTab("RealizarSolicitudes", jPanel4);

        RefrescarInven.setText("Refrescar");
        RefrescarInven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarInvenActionPerformed(evt);
            }
        });

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Presentación", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaInventario);

        VolverASol.setText("Volver a Solicitudes");
        VolverASol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverASolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefrescarInven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VolverASol)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 426, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RefrescarInven)
                    .addComponent(VolverASol))
                .addContainerGap())
        );

        tabbedReportes.addTab("Ver Inventario", jPanel3);

        jLabel4.setText("Aquí puede encontrar las solicitudes que usted ha realizado.");

        tablaVerSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Solicitud", "Fecha", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVerSolicitudes);

        RefrescarSolicitudes.setText("Refrescar");
        RefrescarSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarSolicitudesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RefrescarSolicitudes)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(RefrescarSolicitudes)
                .addContainerGap())
        );

        tabbedReportes.addTab("Mis Solicitudes", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportes)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedReportes)
        );

        TabbedPaneUsuarios.addTab("Reportes", jPanel2);

        jLabel20.setText("Fecha recepción");

        recFecha.setText("jLabel21");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos Proveedor");

        jLabel23.setText("Nombre Proveedor/Prestador del servicio");

        jLabel24.setText("NIT");

        jLabel25.setText("Dirección");

        jLabel26.setText("Celular");

        jLabel27.setText("Telefax");

        rec_nomProv.setText("jLabel30");

        rec_nit.setText("jLabel31");

        rec_dir.setText("jLabel32");

        rec_cel.setText("jLabel33");

        rec_fax.setText("jLabel34");

        tablaDatosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv", "Codigo Interno", "Descripción", "Cantidad", "Presentación", "Valor Unitario", "Valor Total", "Fecha Recepción", "Certificado de calidad", "Cump. Espe", "Fecha Vencimiento", "M. Ver. interna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tablaDatosPedido);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Datos Pedido");

        jLabel36.setText("Subtotal");

        subtotal.setText("jLabel37");

        jLabel38.setText("IVA");

        iva.setText("jLabel39");

        jLabel40.setText("Total");

        total.setText("jLabel41");

        jLabel42.setText("Observaciones");

        recobs.setColumns(20);
        recobs.setRows(5);
        jScrollPane10.setViewportView(recobs);

        jLabel21.setText("Numero de Orden");

        numorden.setText("jLabel28");

        jButton4.setText("Ver Anexo 1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnProcesarRec.setText("Ingresar N° Orden");
        btnProcesarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                .addComponent(recFecha)
                                .addGap(131, 131, 131)
                                .addComponent(btnProcesarRec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(rec_nomProv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numorden))))
                    .addComponent(jLabel35)
                    .addComponent(jLabel23)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(256, 256, 256)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rec_nit)
                            .addComponent(rec_dir)
                            .addComponent(rec_cel)
                            .addComponent(rec_fax)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel38)
                            .addComponent(jLabel40))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtotal)
                            .addComponent(total)
                            .addComponent(iva))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(recFecha)
                    .addComponent(jButton4)
                    .addComponent(btnProcesarRec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rec_nomProv)
                    .addComponent(numorden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rec_nit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(rec_dir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rec_cel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(rec_fax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(iva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );

        btnEnviarRec.setText("Enviar Revisión");
        btnEnviarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarRec)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnEnviarRec)
                .addContainerGap())
        );

        TabbedPaneUsuarios.addTab("Recepción de Pedidos", jPanel8);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(85, 85, 85)
                        .addComponent(ButtonCerrarSesion))
                    .addComponent(TabbedPaneUsuarios))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAdministrador)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonCerrarSesion)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPaneUsuarios)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionActionPerformed
        InicioSesion i = new InicioSesion();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCerrarSesionActionPerformed

    private void BotonVerItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerItemsActionPerformed
        this.RefrescarInven.doClick();
        this.TabbedPaneUsuarios.setSelectedIndex(1);
        this.tabbedReportes.setSelectedIndex(0);
    }//GEN-LAST:event_BotonVerItemsActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Usuario u = cliente.Cliente.conectarU();

        ArrayList<ItemInventario> itemInventario = null;
        try {
            itemInventario = u.itemInventario(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector elementos = new Vector();
        JList list;
        DefaultTableModel df;
        for (ItemInventario i : itemInventario) {
            elementos.add(i.getNumero());
        }
        list = new JList(elementos);
        JOptionPane elegir = new JOptionPane();
        elegir.showConfirmDialog(null, list, "Seleccione el código del ítem", elegir.PLAIN_MESSAGE);
        if (list.getSelectedIndex() != -1) {
            df = (DefaultTableModel) this.tablaIngresarItems.getModel();
            df.addRow(new Object[]{Boolean.FALSE, null, null});
            for (int i = 0; i < df.getRowCount(); i++) {
                df.setValueAt(this.AreaProcesoSolicitante.getText() + "-", i, 0);
            }

            ItemInventario i = itemInventario.get(list.getSelectedIndex());
            df.setValueAt(i.getNumero(), df.getRowCount() - 1, 1);
            df.setValueAt(i.getDescripcion(), df.getRowCount() - 1, 2);
            df.setValueAt(i.getCantidad(), df.getRowCount() - 1, 3);
            df.setValueAt(i.getPresentacion(), df.getRowCount() - 1, 4);
            this.itemsSolicitud.add(i);
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void RefrescarInvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarInvenActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaInventario.getModel();
        for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        Usuario u = cliente.Cliente.conectarU();

        ArrayList<ItemInventario> itemInventario = null;
        try {
            itemInventario = u.itemInventario(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (ItemInventario i : itemInventario) {
            Vector<Object> aux = new Vector<>();
            try {
                aux.add(0, u.area(this.id) + "-" + i.getNumero());
            } catch (RemoteException ex) {
                Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
            }
            aux.add(1, i.getDescripcion());
            aux.add(2, i.getPresentacion());
            aux.add(3, i.getCantidad());
            df.addRow(aux);
        }
    }//GEN-LAST:event_RefrescarInvenActionPerformed

    private void VolverASolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverASolActionPerformed
        this.TabbedPaneUsuarios.setSelectedIndex(0);
        this.jTabbedPane2.setSelectedIndex(0);

    }//GEN-LAST:event_VolverASolActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaIngresarItems.getModel();
        if (df.getRowCount() > 0) {
            this.itemsSolicitud.remove(this.tablaIngresarItems.getSelectedRow());
            df.removeRow(this.tablaIngresarItems.getSelectedRow());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviarActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaIngresarItems.getModel();
        solicitudPr sol = new solicitudPr(hoy, this.Observaciones.getText(), null, this.id, null, null);
        Usuario u = cliente.Cliente.conectarU();

        BigDecimal numSol = null;
        int ite = 0;
        boolean aceptado = true;
        for (ItemInventario i : itemsSolicitud) {
            if (df.getValueAt(ite, 5) != null) {
                i.setCantidadSolicitada(new Float(df.getValueAt(ite, 5).toString()));
                ite++;
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese la cantidad solicitada");

            }
        }
        for (ItemInventario ii : itemsSolicitud) {
            if (ii.getCantidadSolicitada() == 0) {
                aceptado = false;
            }
        }
        if (aceptado == true) {
            try {
                u.crearSolicitud(sol);
                numSol = u.solicitudValida(this.id);

            } catch (RemoteException ex) {
                Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (numSol != null) {
                try {
                    u.itemxsolicitud(this.itemsSolicitud, numSol);
                } catch (RemoteException ex) {
                    Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "El número de la solicitud hecha es:  " + numSol);
            } else {
                JOptionPane.showMessageDialog(null, "No fue posible realizar la solicitud");

            }
        }
        this.RefrescarSolicitudes.doClick();
    }//GEN-LAST:event_BotonEnviarActionPerformed

    private void RefrescarSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarSolicitudesActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaVerSolicitudes.getModel();
        Usuario u = cliente.Cliente.conectarU();

        for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        ArrayList<solicitudPr> solicitudes = null;
        try {
            solicitudes = u.getSolicitud_RA(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
        GregorianCalendar fecha = null;
        for (solicitudPr s : solicitudes) {
            Vector datos = new Vector();
            fecha = s.getFecha();
            datos.add(s.getSolicitudpr_id());
            datos.add(fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
            datos.add(s.getObservaciones());
            df.addRow(datos);
        }
    }//GEN-LAST:event_RefrescarSolicitudesActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaIngresarItems.getModel();
        if (df.getRowCount() > 0) {
            this.itemsSolicitud.remove(this.tablaIngresarItems.getSelectedRow());
            df.removeRow(this.tablaIngresarItems.getSelectedRow());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void botonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar1ActionPerformed
        Usuario u = cliente.Cliente.conectarU();

        ArrayList<ItemInventario> itemInventario = null;
        try {
            itemInventario = u.itemInventario(this.id);
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
        Vector elementos = new Vector();
        JList list;
        DefaultTableModel df;
        for (ItemInventario i : itemInventario) {
            elementos.add(i.getNumero());
        }
        list = new JList(elementos);
        JOptionPane elegir = new JOptionPane();
        elegir.showConfirmDialog(null, list, "Seleccione el código del ítem", elegir.PLAIN_MESSAGE);
        if (list.getSelectedIndex() != -1) {
            df = (DefaultTableModel) this.tablaIngresarItems.getModel();
            df.addRow(new Object[]{Boolean.FALSE, null, null});
            for (int i = 0; i < df.getRowCount(); i++) {
                df.setValueAt(this.AreaProcesoSolicitante.getText() + "-", i, 0);
            }

            ItemInventario i = itemInventario.get(list.getSelectedIndex());
            df.setValueAt(i.getNumero(), df.getRowCount() - 1, 1);
            df.setValueAt(i.getDescripcion(), df.getRowCount() - 1, 2);
            this.itemsSolicitud.add(i);
        }
    }//GEN-LAST:event_botonAgregar1ActionPerformed

    private void BotonVerItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerItems1ActionPerformed
        this.RefrescarInven.doClick();
        this.TabbedPaneUsuarios.setSelectedIndex(1);
        this.tabbedReportes.setSelectedIndex(0);   
    }//GEN-LAST:event_BotonVerItems1ActionPerformed

    private void BotonEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEnviar1ActionPerformed
   /*     DefaultTableModel df = (DefaultTableModel) this.tablaItemsServicios.getModel();
        solicitudServ sol = new solicitudServ(hoy, this.Observaciones.getText(), null, this.id, null, null);//Solicitud Servicios
        Usuario u = cliente.Cliente.conectarU();
        BigDecimal numSol = null;
        int ite = 0;
        boolean aceptado = true;
        
        this.RefrescarSolicitudes.doClick();        // TODO add your handling code here:*/
    }//GEN-LAST:event_BotonEnviar1ActionPerformed

    private void btnProcesarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarRecActionPerformed
        String area =this.area;
        BigDecimal id = this.id;
        BigDecimal orden =null;
        Usuario u = cliente.Cliente.conectarU();
        DefaultTableModel df = (DefaultTableModel) this.tablaDatosPedido.getModel();
        TableColumn cCalidadCell = this.tablaDatosPedido.getColumnModel().getColumn(8);
        TableColumn cEspe = this.tablaDatosPedido.getColumnModel().getColumn(9);
        JComboBox calidad= new JComboBox();
        calidad.addItem("SI");
        calidad.addItem("NO");
        
        JComboBox cEspecificaciones= new JComboBox();
        cEspecificaciones.addItem("SI");
        cEspecificaciones.addItem("NO");
        
        for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        JOptionPane j = new JOptionPane();
        String ordenIngresada = j.showInputDialog("Ingrese el número de orden");
        while(!ordenIngresada.matches("^[0-9][0-9]*") || ordenIngresada.equalsIgnoreCase(""))
        {
            ordenIngresada = j.showInputDialog("Numero de Orden inválido. Ingreselo nuevamente");
            if(j.CANCEL_OPTION==2)
            {
                j.setVisible(false);
            }
        }
        orden = new BigDecimal(ordenIngresada);
        try {
            recepcionProd datosRec = u.getDatosRec(orden, id, area);
            if (datosRec !=null) {
                
            this.rec_nomProv.setText(datosRec.getP().getNombre());
            this.rec_nit.setText(datosRec.getP().getNIT());
            this.rec_dir.setText(datosRec.getP().getDireccion());
            this.rec_fax.setText(new Integer(datosRec.getP().getTelefax()).toString());
            this.rec_cel.setText(new Integer(datosRec.getP().getTelefono()).toString());
            this.numorden.setText(ordenIngresada);
            ArrayList<itemRecep> articulos = datosRec.getArticulos();
                for (itemRecep articulo : articulos) {
                    Vector datos = new Vector();
                    ItemInventario datosCompletosItem = u.datosCompletosItem(articulo.getCinterno(), articulo.getLab());
                    datos.add(datosCompletosItem.getInventario());
                    datos.add(datosCompletosItem.getNumero());
                    datos.add(datosCompletosItem.getDescripcion());
                    datos.add(articulo.getcAprobada());
                    datos.add(datosCompletosItem.getPresentacion());
                    datos.add(articulo.getPrecio());
                    datos.add(articulo.getcAprobada() *articulo.getPrecio());
                    df.addRow(datos);
                    this.recobs.setText(articulo.getObs());
                    float tot = 0;
                    tot+=articulo.getcAprobada() *articulo.getPrecio();
                    this.total.setText(new Float(tot).toString());
                    this.subtotal.setText(new Float(tot*0.84).toString());
                    this.iva.setText(new Float (tot*0.16).toString());
                }
                cCalidadCell.setCellEditor(new DefaultCellEditor(calidad));
                cEspe.setCellEditor(new DefaultCellEditor(cEspecificaciones));
                
                
                
                
                
                
                

            }else
            {
                JOptionPane.showMessageDialog(null, "No se encontró nada referente al número de orden dado");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProcesarRecActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        anexo1 a = new anexo1();
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEnviarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRecActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.tablaDatosPedido.getModel();
        int[] selectedRows = this.tablaDatosPedido.getSelectedRows();
        String numorden = this.numorden.getText();
        ArrayList<itemRecep> articulos = new ArrayList<>();
        itemRecep ii = null;
        Usuario u = cliente.Cliente.conectarU();
        boolean recibirPedido =false;
        for (int i: selectedRows)
        {
            ii = new itemRecep(new BigDecimal(df.getValueAt(i, 1).toString()),df.getValueAt(i, 0).toString() , this.recobs.getText(), new Float(df.getValueAt(i, 3).toString()),new Float(df.getValueAt(i, 5).toString()) );
            ii.setfLlegada((Date)df.getValueAt(i, 7));
            ii.setcCalidad(df.getValueAt(i, 8).toString());
            ii.setcEsp(df.getValueAt(i, 9).toString());
            ii.setfVencimiento((Date)df.getValueAt(i, 10));
            ii.setmVerificacion(df.getValueAt(i, 11));
            articulos.add(ii);
        }
        try {
            recibirPedido = u.recibirPedido(new BigDecimal(numorden), id, area, articulos);
            if(recibirPedido)
            {
                JOptionPane.showMessageDialog(null, "Hecho");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(RArea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarRecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        descargoConsumos d = new descargoConsumos(this.id);
        d.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RArea().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconB.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaProcesoSolicitante;
    private javax.swing.JTextField AreaProcesoSolicitante1;
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JButton BotonEnviar1;
    private javax.swing.JButton BotonVerItems;
    private javax.swing.JButton BotonVerItems1;
    private javax.swing.JButton ButtonCerrarSesion;
    private javax.swing.JTextField NombreSolicitante;
    private javax.swing.JTextField NombreSolicitante1;
    private javax.swing.JTextField Observaciones;
    private javax.swing.JTextField Observaciones1;
    private javax.swing.JButton RefrescarInven;
    private javax.swing.JButton RefrescarSolicitudes;
    private javax.swing.JTabbedPane TabbedPaneUsuarios;
    private javax.swing.JButton VolverASol;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAgregar1;
    private javax.swing.JButton btnEnviarRec;
    private javax.swing.JButton btnProcesarRec;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel fecha1;
    private javax.swing.JLabel iva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelAdministrador;
    private javax.swing.JLabel numorden;
    private javax.swing.JLabel recFecha;
    private javax.swing.JLabel rec_cel;
    private javax.swing.JLabel rec_dir;
    private javax.swing.JLabel rec_fax;
    private javax.swing.JLabel rec_nit;
    private javax.swing.JLabel rec_nomProv;
    private javax.swing.JTextArea recobs;
    private javax.swing.JLabel subtotal;
    private javax.swing.JTabbedPane tabbedReportes;
    private javax.swing.JTable tablaDatosPedido;
    private javax.swing.JTable tablaIngresarItems;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaItemsServicios;
    private javax.swing.JTable tablaVerSolicitudes;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
