/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

import Usuario.Solicitudes.Proc_Solicitudes;
import EstructurasAux.ItemInventario;
import EstructurasAux.itemxproveedor;
import EstructurasAux.proveedor;
import interfaces.Usuario;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Oscar Dario Malagon Murcia
 */
public class Cotizacion extends javax.swing.JFrame {

    private static String id = null;
    private HashMap<String, String> mapProv = new HashMap();
    boolean asociado = false;
    /**
     * Creates new form Cotizacion
     */
    public Cotizacion() {
        initComponents();
    }

    public Cotizacion(String id, String toString, GregorianCalendar fecha, String area, String nombreRA, ArrayList<ItemInventario> items_numSol, String observaciones) throws RemoteException {
        initComponents();
        TableColumn cCalidadCell = this.tablaitemsCot.getColumnModel().getColumn(7);
        DefaultTableModel df_items = (DefaultTableModel) this.tablaitemsCot.getModel();
        JComboBox Apro_NITProv = new JComboBox();
        Cotizacion.id = id;
        this.setLocationRelativeTo(null);
        Usuario u = cliente.Cliente.conectarU();
        ArrayList<proveedor> todosProveedores = u.todosProveedores();
        for (proveedor p : todosProveedores) {
            Apro_NITProv.addItem(p.getNombre());
            mapProv.put(p.getNombre(),p.getNIT());
        }   
        cCalidadCell.setCellEditor(new DefaultCellEditor(Apro_NITProv));

        this.numeroSolicitudCot.setText(toString);
        this.fechaCot.setText(fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1) + "/" + fecha.get(Calendar.YEAR));
        this.areaCot.setText(area);
        this.nombreCot.setText(nombreRA);
        for (ItemInventario i : items_numSol) {
            Object[] datos = new Object[7];
            datos[0] = i.getCantidad();
            datos[1] = i.getInventario();
            datos[2] = i.getNumero();
            datos[3] = i.getDescripcion();
            datos[4] = i.getCantidadSolicitada();
            datos[5] = i.getPresentacion();
            datos[6] = i.getPrecio();
            df_items.addRow(datos);

            tablaitemsCot.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    System.out.println("escucha");
                    String toString = tablaitemsCot.getValueAt(tablaitemsCot.getSelectedRow(), 2).toString();
                    llenarTablaIXP(toString);

                }
            });
        }
        this.setLocationRelativeTo(null);
    }

    private void llenarTablaIXP(String item) {
        Usuario n = cliente.Cliente.conectarU();
        DefaultTableModel df_ixp = (DefaultTableModel) tablaIXP.getModel();
        ArrayList<itemxproveedor> tablaCotizacionesIXP = null;
        for (int i = df_ixp.getRowCount() - 1; i >= 0; i--) {
            df_ixp.removeRow(i);
        }

        try {
            tablaCotizacionesIXP = n.tablaCotizacionesIXP(item);
        } catch (RemoteException ex) {
            Logger.getLogger(Cotizacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (itemxproveedor i : tablaCotizacionesIXP) {
            Object[] datos = new Object[5];
            datos[0] = i.getNIT();
            datos[1] = i.getNombre();
            datos[2] = i.getCinterno();
            datos[3] = i.getInv();
            datos[4] = i.getPrecio();
            df_ixp.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nombreCot = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        areaCot = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fechaCot = new javax.swing.JLabel();
        numeroSolicitudCot = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BotonAyudaCot = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaitemsCot = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIXP = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        obsCot = new javax.swing.JTextField();
        BotonRevisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreCot.setText("      ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Nombre de Solicitante");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Area o proceso Solicitante");

        areaCot.setText("    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCot)
                    .addComponent(areaCot))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaCot)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCot)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        fechaCot.setText("    ");

        numeroSolicitudCot.setText("     ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Fecha");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("N° Solicitud");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaCot)
                    .addComponent(numeroSolicitudCot))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(numeroSolicitudCot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaCot)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        BotonAyudaCot.setText("Ayuda");
        BotonAyudaCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAyudaCotActionPerformed(evt);
            }
        });

        tablaitemsCot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv Actual", "Lab", "Código", "Descripción", "Cantidad Solicitada", "Presentación", "Precio Unitario", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaitemsCot);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Item por Proveedor");

        tablaIXP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Nombre", "Cod Interno", "Inventario", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaIXP);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Observaciones");

        BotonRevisar.setText("Enviar Cotización");
        BotonRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Cotización");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(46, 46, 46)
                                .addComponent(BotonAyudaCot))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(obsCot)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonRevisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotonAyudaCot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(obsCot, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRevisar)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAyudaCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAyudaCotActionPerformed
        JOptionPane.showMessageDialog(areaCot, "Antes de enviar la cotización debe seleccionar"
                + "todas las filas que desea actualizar. \nPuede ayudarse con el boton Ctrl");
    }//GEN-LAST:event_BotonAyudaCotActionPerformed

    private void BotonRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevisarActionPerformed
        Usuario u = cliente.Cliente.conectarU();
        boolean act = false;
        boolean actPrecio = false;
        DefaultTableModel df_itemsCot = (DefaultTableModel) this.tablaitemsCot.getModel();
        int itemsAct[] = this.tablaitemsCot.getSelectedRows();
        BigDecimal numSol = new BigDecimal(this.numeroSolicitudCot.getText());
        String lab;
        String codigo;
        String proveedor;
        float precio;
        for (int ite : itemsAct) {
            lab = (String) df_itemsCot.getValueAt(ite, 1);
            codigo = df_itemsCot.getValueAt(ite, 2).toString();
            precio = new Float(df_itemsCot.getValueAt(ite, 6).toString());
            try {
                proveedor = this.mapProv.get(df_itemsCot.getValueAt(ite, 7).toString());
                System.out.println(id + " " + codigo + " " + lab + " " + numSol + " " + precio);
                actPrecio = u.generarCotizacion(id, proveedor, codigo, lab, numSol, precio);
                
                
                
                DefaultTableModel dfixp =(DefaultTableModel) tablaIXP.getModel();
                
                ArrayList<ItemInventario> itemxProv = u.itemxProv(proveedor, codigo);
                if(itemxProv.size()==0)
                {
                    u.asociarItem(codigo, proveedor, Float.toString(precio));
                        JOptionPane.showMessageDialog(null, "El proveedor seleccionado no estaba asociado al ítem.\nSe acaba de asociar con los siguientes parámetros:"
                                + "\nCódigo: "+codigo +"\nPrecio: " + precio);
                }else{
                for (ItemInventario i : itemxProv) {
                    System.out.println(i.getNumero());
                    if(i.getNumero().equalsIgnoreCase(codigo))
                    {
                        asociado = true;
                        System.out.println("entro");
                    }else
                    {
                        
                        break;
                    }
                }
                }
                
            } catch (RemoteException ex) {
                Logger.getLogger(Cotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            act = u.RevisarSolicitud(Cotizacion.id, numSol, "SI");
        } catch (RemoteException ex) {
            Logger.getLogger(Cotizacion.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (act == true && actPrecio == true) {
            JOptionPane.showMessageDialog(rootPane, "Hecho!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error Actualizando");
        }
    }//GEN-LAST:event_BotonRevisarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Proc_Solicitudes sol = new Proc_Solicitudes(Cotizacion.id);
        sol.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAyudaCot;
    private javax.swing.JButton BotonRevisar;
    private javax.swing.JLabel areaCot;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel fechaCot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nombreCot;
    private javax.swing.JLabel numeroSolicitudCot;
    private javax.swing.JTextField obsCot;
    private javax.swing.JTable tablaIXP;
    private javax.swing.JTable tablaitemsCot;
    // End of variables declaration//GEN-END:variables
}
