/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package responsableArea;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class anexo1 extends javax.swing.JFrame {

    /**
     * Creates new form anexo1
     */
    public anexo1() {
        initComponents();
        DefaultTableModel df = (DefaultTableModel)this.jTable1.getModel();
        this.jTable1.setRowHeight(this.jTable1.getRowHeight()+70);
        this.setSize(1725,780);
        String [] fila1 = {"1", "Medios \n\n\n\nde cultivo", "Afecta Significativamente","ECOMETRICOS,Certificado de calidad", "Pruebas de productividad y selectividad antes del uso y certificados de calidad", "Por lote recibido"};
        String [] fila2 = {"2", "Reactivo e insumos de lab", "Afecta medianamente", "Certificados de calidad, CUMPLIMIENTO REQUISITOS O.C", "Inspección visual en recepción", "En cada compra"};
        String [] fila3 = {"3","Material de lab", "Afecta medianamente", "Certificado de calidad. CUMPLIMIENTO REQUISITOS O.C", "Inspección visual en recepción", "En cada compra"};
        String [] fila4 = {"4", "Insumos de oficinas y otros", "No afecta", "NO REQUIERE", "No requiere control", "-"};
        String [] fila5 = {"5", "Servicios generales", "No afecta", "NO REQUIERE", "No requiere control", "-"};
        String [] fila6 = {"6", "Equipos, calibración y servicios de mantto", "Afecta Significativamente","Certificaciones.Patrones de calibración\nPRUEBAS DE USO EQUIPOS", "Control en laboratorio durante la recepción mediante pruebas", "En cada servicio"};
        String [] fila7 = {"7", "Contrataciones externas\n(Lab externo)", "Afecta Significativamente","AUDITORIA", "Requiere control en instalación de proveedor", "Anual"};
        df.addRow(fila1);
        df.addRow(fila2);
        df.addRow(fila3);
        df.addRow(fila4);
        df.addRow(fila5);
        df.addRow(fila6);
        df.addRow(fila7);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAdministrador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        labelAdministrador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelAdministrador.setText("TIPO Y GRADO DE CONTROL SOBRE PROVEEDORES Y PRODUCTOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLASE", "PRODUCTO", "IMPACTO EN POSTERIOR REALIZACION DEL SERVICIO", "CONTROLES ESTABLECIDOS", " ", "FRECUENCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(270);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(270);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(270);
            jTable1.getColumnModel().getColumn(2).setMinWidth(320);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(320);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(320);
            jTable1.getColumnModel().getColumn(3).setMinWidth(470);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(470);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(470);
            jTable1.getColumnModel().getColumn(4).setMinWidth(470);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(470);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(470);
            jTable1.getColumnModel().getColumn(5).setMinWidth(110);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(110);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(110);
        }

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anexo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anexo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anexo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anexo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anexo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAdministrador;
    // End of variables declaration//GEN-END:variables
}
