/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario.Creaciones;

import EstructurasAux.proveedor;
import Usuario.MenuPrincipal;
import interfaces.Usuario;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Oscar Darío Malagón Murcia
 */
public class CrearProveedor extends javax.swing.JFrame {

    private static String id = null;
    private static String tabla = "";
    private static Boolean existia = false;

    /**
     * Creates new form creaciones
     */
    public CrearProveedor() {
        initComponents();
    }

    public CrearProveedor(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        CrearProveedor.id = id;
        setIcon();
        jtf_nit.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {

                Usuario u = cliente.Cliente.conectarU();
                try {
                    proveedor datosProveedor = u.getDatosProveedor(jtf_nit.getText());
                    if (datosProveedor != null) {
                        jtf_nombre.setText(datosProveedor.getNombre());
                        jtf_dir.setText(datosProveedor.getDireccion());
                        jtf_tel.setText(datosProveedor.getTelefono());
                        jtf_fax.setText(datosProveedor.getTelefax());
                        jtf_ciudad.setText(datosProveedor.getCiudad());
                        jtf_correo.setText(datosProveedor.getCorreo());
                        jtf_cel.setText(datosProveedor.getCelular());
                        jtf_contacto.setText(datosProveedor.getContacto());
                        
                        existia = true;
                    }
                } catch (RemoteException ex) {
                    Logger.getLogger(CrearProveedor.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                jtf_nombre.setText("");
                jtf_dir.setText("");
                jtf_tel.setText("");
                jtf_fax.setText("");
                jtf_ciudad.setText("");
                jtf_correo.setText("");
                jtf_cel.setText("");
                jtf_contacto.setText("");
                existia = false;
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                System.out.println("cambiando el valor");

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jlb_titulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtf_nit = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_dir = new javax.swing.JTextField();
        jtf_tel = new javax.swing.JTextField();
        jtf_fax = new javax.swing.JTextField();
        jtf_ciudad = new javax.swing.JTextField();
        jtf_correo = new javax.swing.JTextField();
        jtf_cel = new javax.swing.JTextField();
        jtf_contacto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lbl_nit = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_dir = new javax.swing.JLabel();
        lbl_tel = new javax.swing.JLabel();
        lbl_fax = new javax.swing.JLabel();
        lbl_ciudad = new javax.swing.JLabel();
        lbl_pais = new javax.swing.JLabel();
        lbl_pais1 = new javax.swing.JLabel();
        lbl_pais2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jlb_titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlb_titulo.setText("Creación de Proveedor");

        jtf_nit.setMaximumSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_nit, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jtf_nombre)
                    .addComponent(jtf_dir)
                    .addComponent(jtf_tel)
                    .addComponent(jtf_fax)
                    .addComponent(jtf_ciudad)
                    .addComponent(jtf_correo)
                    .addComponent(jtf_cel)
                    .addComponent(jtf_contacto))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtf_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jtf_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbl_nit.setText("NIT");

        lbl_nombre.setText("Nombre");

        lbl_dir.setText("Dirección");

        lbl_tel.setText("Teléfono");

        lbl_fax.setText("Telefax");

        lbl_ciudad.setText("Ciudad");

        lbl_pais.setText("Correo");

        lbl_pais1.setText("Celular");

        lbl_pais2.setText("Contacto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nit)
                    .addComponent(lbl_pais)
                    .addComponent(lbl_ciudad)
                    .addComponent(lbl_fax)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_dir)
                    .addComponent(lbl_tel)
                    .addComponent(lbl_pais1)
                    .addComponent(lbl_pais2))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nit)
                .addGap(18, 18, 18)
                .addComponent(lbl_nombre)
                .addGap(18, 18, 18)
                .addComponent(lbl_dir)
                .addGap(18, 18, 18)
                .addComponent(lbl_tel)
                .addGap(18, 18, 18)
                .addComponent(lbl_fax)
                .addGap(18, 18, 18)
                .addComponent(lbl_ciudad)
                .addGap(18, 18, 18)
                .addComponent(lbl_pais)
                .addGap(18, 18, 18)
                .addComponent(lbl_pais1)
                .addGap(18, 18, 18)
                .addComponent(lbl_pais2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Creación", jPanel1);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAceptar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (!existia) {
            this.crearProv();
        } else {
            this.editarProv();
        }
     }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        MenuPrincipal menu = new MenuPrincipal(id);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CrearProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlb_titulo;
    private javax.swing.JTextField jtf_cel;
    private javax.swing.JTextField jtf_ciudad;
    private javax.swing.JTextField jtf_contacto;
    private javax.swing.JTextField jtf_correo;
    private javax.swing.JTextField jtf_dir;
    private javax.swing.JTextField jtf_fax;
    private javax.swing.JTextField jtf_nit;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_tel;
    private javax.swing.JLabel lbl_ciudad;
    private javax.swing.JLabel lbl_dir;
    private javax.swing.JLabel lbl_fax;
    private javax.swing.JLabel lbl_nit;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_pais;
    private javax.swing.JLabel lbl_pais1;
    private javax.swing.JLabel lbl_pais2;
    private javax.swing.JLabel lbl_tel;
    // End of variables declaration//GEN-END:variables

    private void crearProv() {
        Usuario u = cliente.Cliente.conectarU();
        boolean valido;
        try {
            valido = u.CrearProveedor(
                    this.jtf_nit.getText(), this.jtf_nombre.getText(), this.jtf_dir.getText(), this.jtf_tel.getText(), 
                    this.jtf_fax.getText(), this.jtf_ciudad.getText(), this.jtf_correo.getText(), this.jtf_cel.getText(), this.jtf_contacto.getText()
                );
            if (valido) {
                JOptionPane.showMessageDialog(null, "Proveedor Creado");
            } else {
                JOptionPane.showMessageDialog(null, "Error creando al proveedor");
            }

        } catch (RemoteException ex) {
            Logger.getLogger(CrearProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void editarProv() {
        Usuario u = cliente.Cliente.conectarU();
        boolean valido;
        try {
            valido = u.EditarProveedor(
                    this.jtf_nit.getText(), this.jtf_nombre.getText(), this.jtf_dir.getText(), this.jtf_tel.getText(),
                    this.jtf_fax.getText(), this.jtf_ciudad.getText(), this.jtf_correo.getText(), this.jtf_cel.getText(),
                    this.jtf_contacto.getText()
            
            );
            if (valido) {
                JOptionPane.showMessageDialog(null, "Proveedor Editado");
            } else {
                JOptionPane.showMessageDialog(null, "Error creando al proveedor");
            }

        } catch (RemoteException ex) {
            Logger.getLogger(CrearProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconB.png")));
    }
}
