/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario.Creaciones;

import EstructurasAux.permisos;
import Usuario.MenuPrincipal;
import cliente.Cliente;
import interfaces.Usuario;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oscar Dario Malagon Murcia
 */
public class PermisosUsuario extends javax.swing.JFrame {

    private static String id = null;
    private String idUsNuevo = "";

    /**
     * Creates new form PermisosUsuario
     */
    public PermisosUsuario() {
        initComponents();
    }

    public PermisosUsuario(String id, String idUsNuevo) throws RemoteException {
        initComponents();
        PermisosUsuario.id = id;
        this.idUsNuevo = idUsNuevo;
        this.setLocationRelativeTo(null);
        DefaultTableModel df = (DefaultTableModel) this.jTable1.getModel();

        for (int i = 0; i < df.getRowCount(); i++) {
            df.setValueAt(false, i, 2);
        }
        Usuario u = Cliente.conectarU();
        permisos lista = u.lista(idUsNuevo);
        if (lista != null) {
            List<Integer> lstPermisos = new ArrayList<>();
            lstPermisos.add(lista.isCrearItem());
            lstPermisos.add(lista.isCrearProveedor());
            lstPermisos.add(lista.isCrearUsuario());
            lstPermisos.add(lista.isDescargarConsumos());
            lstPermisos.add(lista.isRecibirPedidos());
            lstPermisos.add(lista.isGenRepDescargos());
            lstPermisos.add(lista.isGenRepInventario());
            lstPermisos.add(lista.isGenRepUsuarios());
            lstPermisos.add(lista.isGenRepProveedores());
            lstPermisos.add(lista.isGenRepItemxProveedor());
            lstPermisos.add(lista.isSolicitarProductos());
            lstPermisos.add(lista.isRealizarCotizaciones());
            lstPermisos.add(lista.isAprobarCotizaciones());
            lstPermisos.add(lista.isGenerarOrdenesCompra());
            lstPermisos.add(lista.isBloquearUsuario());
            lstPermisos.add(lista.getGenfdc001());
            for (int i = 0; i < lstPermisos.size(); i++) {
                df.setValueAt((lstPermisos.get(i) == 1 ? true : false), i, 2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_volver = new javax.swing.JLabel();
        lbl_volver1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_titulo.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlb_titulo.setText("Permisos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Gestionar Item", null},
                {"2", "Gestionar Proveedor",  new Boolean(false)},
                {"3", "Gestionar Usuario", null},
                {"4", "Descargar Consumos", null},
                {"5", "Recibir/Devolver  Pedidos", null},
                {"6", "Generar Reporte Descargos", null},
                {"7", "Generar Reporte Inventario", null},
                {"8", "Generar Reporte Usuarios", null},
                {"9", "Generar Reporte Proveedores", null},
                {"10", "Generar Reporte Item x Proveedor", null},
                {"11", "Solicitar Productos", null},
                {"12", "Gestionar Solicitudes", null},
                {"13", "Generar Reporte Solicitudes", null},
                {"14", "Generar Reporte Ordenes de Compra", null},
                {"15", "Bloquear Usuario", null},
                {"16", "Generar Reporte Recepciones", null}
            },
            new String [] {
                "Id", "Permiso", "Asignado?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbl_volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_volver.setText("Volver");

        lbl_volver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_volver1.setText("Asignar Permisos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OK.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NO.png"))); // NOI18N
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_volver1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbl_volver1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_volver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Volver, jButton1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_titulo)
                        .addGap(0, 527, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_titulo)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 84, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel df = (DefaultTableModel) this.jTable1.getModel();
        ArrayList<Integer> listado = new ArrayList<>();
        Usuario u = cliente.Cliente.conectarU();
        for (int i = 0; i < df.getRowCount(); i++) {
            boolean aux = (Boolean) jTable1.getValueAt(i, 2);
            if (aux) {
                listado.add(1);
            } else {
                listado.add(0);
            }

        }
        
        permisos per = new permisos(this.idUsNuevo, listado.get(0), listado.get(1), listado.get(2), listado.get(3),
                listado.get(4), listado.get(5), listado.get(6),
                listado.get(7), listado.get(8), listado.get(9),
                listado.get(10), listado.get(11), listado.get(12),
                listado.get(13), listado.get(14), listado.get(15));
        try {
            boolean AsignarPermisos = u.AsignarPermisos(per);
            if (AsignarPermisos) {
                JOptionPane.showMessageDialog(null, "Los permisos han sido asignados");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(PermisosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermisosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermisosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermisosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermisosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermisosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlb_titulo;
    private javax.swing.JLabel lbl_volver;
    private javax.swing.JLabel lbl_volver1;
    // End of variables declaration//GEN-END:variables
}
