/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario.Reportes;

import EstructurasAux.infoItems;
import Usuario.Recepciones.*;
import Formatos.fdc002;
import Formatos.fdc002Recepciones;
import Usuario.solicitudes.MenuSolicitud;
import com.toedter.calendar.JDateChooserCellEditor;
import interfaces.Usuario;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import logica.DatosFormatos;
import logica.EvProv;
import logica.ItemInventario;
import logica.ItemRecep;
import logica.RecepcionProd;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class ReporteRecepciones extends javax.swing.JFrame {

    private static String id = null;
    private static final GregorianCalendar hoy = new GregorianCalendar();

    /**
     * Creates new form Recepciones
     */
    public ReporteRecepciones() {
        initComponents();
    }

    public ReporteRecepciones(String id) {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            ReporteRecepciones.id = id;
            TableColumn fecRec = this.tablaDatosPedido.getColumnModel().getColumn(7);
            fecRec.setCellEditor(new JDateChooserCellEditor());
            TableColumn fecVen = this.tablaDatosPedido.getColumnModel().getColumn(10);
            fecVen.setCellEditor(new JDateChooserCellEditor());
            this.jlblrecFecha.setText(getFecha());
            setIcon();

            tablaOrdenes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    llenarInfo();
                }
            });
            llenarOrdenes();
        } catch (RemoteException ex) {
            Logger.getLogger(ReporteRecepciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInicioSesion = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jlblrecFecha = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaDatosPedido = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        recobs = new javax.swing.JTextArea();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ev1 = new javax.swing.JComboBox<String>();
        ev3 = new javax.swing.JComboBox<String>();
        ev4 = new javax.swing.JComboBox<String>();
        ev2 = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ev5 = new javax.swing.JComboBox<String>();
        ev7 = new javax.swing.JComboBox<String>();
        ev8 = new javax.swing.JComboBox<String>();
        ev6 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnEnviarRec = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        rec_dir = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rec_cel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rec_nomProv = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        rec_nit = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        rec_fax = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labelInicioSesion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelInicioSesion.setText("Reporte Pedidos");

        jLabel20.setText("Fecha recepción");

        tablaDatosPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Inv", "Codigo Interno", "Descripción", "Cantidad", "Presentación", "Valor Unitario", "Valor Total", "Fecha Recepción", "Certificado de calidad", "Cump. Espe", "Fecha Vencimiento", "M. Ver. interna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tablaDatosPedido);
        if (tablaDatosPedido.getColumnModel().getColumnCount() > 0) {
            tablaDatosPedido.getColumnModel().getColumn(11).setResizable(false);
        }

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Datos Pedido");

        jLabel40.setText("Total");

        jLabel42.setText("Observaciones");

        recobs.setColumns(20);
        recobs.setLineWrap(true);
        recobs.setRows(5);
        jScrollPane10.setViewportView(recobs);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Evaluación del Servicio");

        ev1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        jLabel2.setText("1. Servicio Preventa");

        jLabel3.setText("2. Atención usuario");

        jLabel4.setText("3. Sistema de calidad");

        jLabel5.setText("4. Fecha de entrega");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ev2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        ev5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        ev6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "0", "NA" }));

        jLabel6.setText("5. Entrega Pedidos completos a tiempo");

        jLabel7.setText("6. Cumplimiento de Requisitos");

        jLabel8.setText("7. Entrega de certificados de calidad");

        jLabel9.setText("8. Conformidad con el servicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ev6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ev8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ev8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnEnviarRec.setText("Generar Archivo");
        btnEnviarRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarRecActionPerformed(evt);
            }
        });

        jLabel23.setText("Nombre Proveedor/Prestador del servicio");

        rec_dir.setText("fffff");

        jLabel24.setText("NIT");

        rec_cel.setText("cccc");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Datos Proveedor");

        rec_nomProv.setText("ffff");

        jLabel26.setText("Celular");

        rec_nit.setText("oooo");

        jLabel25.setText("Dirección");

        rec_fax.setText("sss");

        jLabel27.setText("Telefax");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(rec_nomProv))
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(256, 256, 256)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rec_nit)
                            .addComponent(rec_dir)
                            .addComponent(rec_cel)
                            .addComponent(rec_fax))))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rec_nomProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rec_nit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(rec_dir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rec_cel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(rec_fax))
                .addContainerGap())
        );

        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Orden"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaOrdenes);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblrecFecha)
                        .addGap(422, 422, 422))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 345, Short.MAX_VALUE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarRec))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel1)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jlblrecFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(total))
                .addGap(1, 1, 1)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviarRec)
                            .addComponent(btnVolver)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInicioSesion)
                        .addGap(0, 1000, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarRecActionPerformed
        {
            DefaultTableModel df = (DefaultTableModel) this.tablaDatosPedido.getModel();
            String numorden1 = this.tablaOrdenes.getValueAt(this.tablaOrdenes.getSelectedRow(), 0).toString();
            ArrayList<infoItems> lstItems = new ArrayList<>();
            for (int i = 0; i < df.getRowCount(); i++) {
                lstItems.add(new infoItems(
                        df.getValueAt(i, 1).toString(),
                        df.getValueAt(i, 2).toString(),
                        df.getValueAt(i, 3).toString(),
                        df.getValueAt(i, 4).toString(),
                        df.getValueAt(i, 5).toString(),
                        df.getValueAt(i, 6).toString(),
                        df.getValueAt(i, 7).toString(),
                        df.getValueAt(i, 8).toString(),
                        df.getValueAt(i, 9).toString(),
                        df.getValueAt(i, 10).toString(),
                        df.getValueAt(i, 11).toString()));
            }
            System.out.println(df.getValueAt(0, 8).toString());
            EvProv evProv = new EvProv();
            evProv.setNit(this.rec_nit.getText());
            evProv.setNumorden(new Double(numorden1));
            evProv.setEv1(this.ev1.getSelectedItem().toString());
            evProv.setEv2(this.ev2.getSelectedItem().toString());
            evProv.setEv3(this.ev3.getSelectedItem().toString());
            evProv.setEv4(this.ev4.getSelectedItem().toString());
            evProv.setEv5(this.ev5.getSelectedItem().toString());
            evProv.setEv6(this.ev6.getSelectedItem().toString());
            evProv.setEv7(this.ev7.getSelectedItem().toString());
            evProv.setEv8(this.ev8.getSelectedItem().toString());
            JOptionPane.showMessageDialog(null, "Recopilando información...");
            DatosFormatos datos = getDatos("2");
            String rutaImagen;
            String property = System.getProperty("user.dir");
            rutaImagen = property.concat("\\src\\Imagenes\\iconB.png");
            HashMap<String, String> parametros = new HashMap<>();
            parametros.put("image", rutaImagen);
            parametros.put("fechaElab", getFecha());
            parametros.put("oCompra", this.tablaOrdenes.getValueAt(this.tablaOrdenes.getSelectedRow(), 0).toString());
            parametros.put("revision", datos.getRevision());
            parametros.put("fechaact", datos.getFechaActualizacion());
            parametros.put("titulo", datos.getTitulo());
            parametros.put("Obs", this.recobs.getText());
            parametros.put("subtotal", this.total.getText());
            parametros.put("nit", this.rec_nit.getText());
            parametros.put("nombreProv", this.rec_nomProv.getText());
            parametros.put("direccionProv", this.rec_dir.getText() + "-" + this.rec_cel.getText());
            parametros.put("fax", this.rec_fax.getText());
            parametros.put("1_sPreventa", this.ev1.getSelectedItem().toString());
            parametros.put("2_AUsuario", this.ev2.getSelectedItem().toString());
            parametros.put("3_SCalidad", this.ev3.getSelectedItem().toString());
            parametros.put("4_fEntrega", this.ev4.getSelectedItem().toString());
            parametros.put("5_completos", this.ev5.getSelectedItem().toString());
            parametros.put("6_CRequisitos", this.ev6.getSelectedItem().toString());
            parametros.put("7_CCalidad", this.ev7.getSelectedItem().toString());
            parametros.put("8_Conformidad", this.ev8.getSelectedItem().toString());
            JFileChooser chooser = new JFileChooser();
            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            chooser.showOpenDialog(this);
            String path = chooser.getSelectedFile().getPath();
            File archivo = fdc002Recepciones.metodo(path, parametros, lstItems);
            if (JOptionPane.showConfirmDialog(null, "¿Desea abrir el archivo?", "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    Desktop.getDesktop().open(archivo);
                } catch (IOException ex) {
                    Logger.getLogger(ReporteSolicitudes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }    }//GEN-LAST:event_btnEnviarRecActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuReportes menu = new MenuReportes(id);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteRecepciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ReporteRecepciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarRec;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> ev1;
    private javax.swing.JComboBox<String> ev2;
    private javax.swing.JComboBox<String> ev3;
    private javax.swing.JComboBox<String> ev4;
    private javax.swing.JComboBox<String> ev5;
    private javax.swing.JComboBox<String> ev6;
    private javax.swing.JComboBox<String> ev7;
    private javax.swing.JComboBox<String> ev8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlblrecFecha;
    private javax.swing.JLabel labelInicioSesion;
    private javax.swing.JLabel rec_cel;
    private javax.swing.JLabel rec_dir;
    private javax.swing.JLabel rec_fax;
    private javax.swing.JLabel rec_nit;
    private javax.swing.JLabel rec_nomProv;
    private javax.swing.JTextArea recobs;
    private javax.swing.JTable tablaDatosPedido;
    private javax.swing.JTable tablaOrdenes;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconB.png")));
    }

    private void llenarInfo() {
        BigDecimal orden;
        DefaultTableModel df = (DefaultTableModel) this.tablaDatosPedido.getModel();

        for (int i = df.getRowCount() - 1; i >= 0; i--) {
            df.removeRow(i);
        }
        String ordenIngresada = this.tablaOrdenes.getValueAt(this.tablaOrdenes.getSelectedRow(), 0).toString();
        orden = new BigDecimal(ordenIngresada);
        RecepcionProd datosRec = getDatosPedidoRecibido(orden, this.id);
        if (datosRec != null) {
            
            this.rec_nomProv.setText(datosRec.getP().getNombre());
            this.rec_nit.setText(datosRec.getP().getNIT());
            this.rec_dir.setText(datosRec.getP().getDireccion());
            this.rec_fax.setText(datosRec.getP().getTelefax());
            this.rec_cel.setText(datosRec.getP().getTelefono());
            this.recobs.setText(datosRec.getObservaciones());
            ArrayList<ItemRecep> articulos = (ArrayList<ItemRecep>) datosRec.getArticulos();
            float tot = 0;
            int i = 0;
            for (ItemRecep articulo : articulos) {
                ItemInventario d = buscarInfoItem(articulo.getCinterno());
                Object[] datos = new Object[12];
                datos[0] = d.getInventario();
                datos[1] = d.getNumero();
                datos[2] = d.getDescripcion();
                datos[3] = articulo.getCAprobada();
                datos[4] = d.getPresentacion();
                datos[5] = articulo.getPrecio();
                datos[6] = articulo.getCAprobada() * articulo.getPrecio();
                datos[7] = articulo.getFLlegada();
                datos[8] = articulo.getCCalidad();
                datos[9] = articulo.getCEsp();
                datos[10] = articulo.getFVencimiento();
                datos[11] = articulo.getMVerificacion().toString();
                df.addRow(datos);
                this.recobs.setText(articulo.getObs());
                tot += articulo.getCAprobada() * articulo.getPrecio();
                this.total.setText(Float.toString(tot));
            }
            EvProv ev = getEvaluacionProv(new Double(orden.toString()));
            if (ev != null) {
                
                this.ev1.setSelectedItem(ev.getEv1());
                this.ev2.setSelectedItem(ev.getEv2());
                this.ev3.setSelectedItem(ev.getEv3());
                this.ev4.setSelectedItem(ev.getEv4());
                this.ev5.setSelectedItem(ev.getEv5());
                this.ev6.setSelectedItem(ev.getEv6());
                this.ev7.setSelectedItem(ev.getEv7());
                this.ev8.setSelectedItem(ev.getEv8());
                this.ev1.setEditable(false);
                this.ev2.setEditable(false);
                this.ev3.setEditable(false);
                this.ev4.setEditable(false);
                this.ev5.setEditable(false);
                this.ev6.setEditable(false);
                this.ev7.setEditable(false);
                this.ev8.setEditable(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró nada referente al número de orden dado");
        }
    }

    private void llenarOrdenes() throws RemoteException {
        DefaultTableModel dfOrdenes = (DefaultTableModel) this.tablaOrdenes.getModel();
        for (int i = dfOrdenes.getRowCount() - 1; i >= 0; i--) {
            dfOrdenes.removeRow(i);
        }
        ArrayList<Integer> numerosDeOrden = (ArrayList<Integer>) numerosDeOrdenRecibidas();
        for (Integer i : numerosDeOrden) {
            Object[] infoItems = new Object[8];
            infoItems[0] = i;
            dfOrdenes.addRow(infoItems);
        }
    }

    private static String getFecha() {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.getFecha();
    }

    private static DatosFormatos getDatos(java.lang.String id) {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.getDatos(id);
    }

    private static String getFecha_1() {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.getFecha();
    }

    private static RecepcionProd getDatosPedidoRecibido(java.math.BigDecimal numorden, java.lang.String id) {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.getDatosPedidoRecibido(numorden, id);
    }

    private static ItemInventario buscarInfoItem(java.lang.String cinterno) {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.buscarInfoItem(cinterno);
    }

    private static EvProv getEvaluacionProv(double numorden) {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.getEvaluacionProv(numorden);
    }

    private static java.util.List<java.lang.Integer> numerosDeOrdenRecibidas() {
        logica.LogicaBiotrends_Service service = new logica.LogicaBiotrends_Service();
        logica.LogicaBiotrends port = service.getLogicaBiotrendsPort();
        return port.numerosDeOrdenRecibidas();
    }
}
